### ISSUE TITLE
Track ERC2309 compliant ERC721s

### ISSUE THREAD

**Issue by ernestognw** [alephao/solidity-benchmarks#15]
## Description
I've recently updated both OpenZeppelin contracts (#12), ERC721A (#13), and both now support a consecutive minting according to ERC2309. However, the current way of adding a new variation and test its implementation is not compatible with this test case.

The reason behind this is that when the `ConsecutiveTransfer` event is emitted outside of the constructor, the contract is not ERC721 compatible anymore as stated in the [ERC721A comments](https://github.com/chiru-labs/ERC721A/blob/main/contracts/ERC721A.sol#L799) and also [restricted on OpenZeppelin Contracts](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Consecutive.sol#L89).

I think both ERC2309 implementations are worth reviewing and benchmarking. I can take care by myself and send a PR, however, I'd love some feedback before moving forward.

## Context

I tried following the README steps in order to add a new variant, this is an example of what I was thinking for an `ERC721_OZConsecutive`:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.4;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {ERC721Consecutive} from "@openzeppelin/contracts/token/ERC721/extensions/ERC721Consecutive.sol";

contract ERC721_OZConsecutive is ERC721Consecutive {
    uint256 currentSupply;

    constructor() ERC721("Name", "Sy") {}

    function mint(address to, uint96 amount) external payable {
        uint256 startingIndex;
        unchecked {
            startingIndex = currentSupply + 1;
            currentSupply += amount;
        }

        _mintConsecutive(to, amount);
    }
    
    ...
}
```

However, it fails because the `_mintConsecutive(to, amount)` is called outside the constructor, and I don't see an easy workaround.

Right now my best approach is to add an alternative `test_deploy` with the consecutive minting for ERC2309-compliant tokens, but I wanted to open a discussion before sending the PR.

I'd love feedback @alephao

**Comment by alephao** [comment]
Hi @ernestognw, 

I wasn't familiar with this ERC, I just finished reading it and checked the links you sent.

> Right now my best approach is to add an alternative test_deploy with the consecutive minting for ERC2309-compliant tokens, but I wanted to open a discussion before sending the PR.

I agree. I also don't think it's worth it doing a `_mintConsecutive` benchmark outside of the constructor because it seem like it is not supposed to be used outside of it since it breaks the ERC721 standard like you mentioned. So if we're doing just the constructor benchmark, we can maybe add a table below the `deploy` table, maybe something like:

**How much gas to deploy the ERC2309 compliant contracts when minting N tokens in the constructor?**

Implementation | 1 | 100 | 1000 | 10000
-- | -- | -- | -- | --
ERC721A | 1000 | 2000 | 3000 | 4000
OpenZeppelin Consecutive | 1000 | 2000 | 3000 | 4000

---

> However, it fails because the _mintConsecutive(to, amount) is called outside the constructor, and I don't see an easy workaround.

For the tests we can have a mock that just calls the `_mintConsecutive` in the constructor e.g:

```solidity
// ... imports
contract ERC721_OZConsecutive is ERC721Consecutive {
    constructor(uint96 amount) ERC721("Name", "Sy") {
        // Just passing any random address so we don't have to do it in the test functions
        _mintConsecutive(0x1000000000000000000000000000000000000000, amount);
    }
}
```

then for the test functions we just create a new instance of that mock contract and pass the amount 

```solidity
// ...imports
contract ERC721_OZConsecutive_deploy_Test is ERC721Consecutive {
    function test_deploy_1() public {
        ERC721OZConsecutive sut = new ERC721OZConsecutive(1)
    }

    function test_deploy_1000() public {
        ERC721OZConsecutive sut = new ERC721OZConsecutive(1000)
    }
  
   // ...
}
```

Le me know what you think!

**Comment by ernestognw** [comment]
Thank you very much @alephao, your explanation was really helpful. I started doing some experiments with what you suggested and  I just sent a new PR including the ERC721-ERC2309 variations and updated the docs and scripts.

I have the feeling that is kinda complicated to follow the instructions for ERC2309 tokens, but I don't think it should be thought as a new variation (separated from ERC721). From your examples I assume you'd think the same.

Let me know your thoughts :D
